- hosts: localhost
  vars:
    names: [ {
      "first": "Paul",
      "last": "Thompson",
      "mobile": "+1-234-31245543",
      "ctc": "100000",
      "address": {
         "city": "LasVegas",
         "country": "USA"
         }
         },
         {
      "first": "Sarav",
      "last": "AK",
      "mobile": "+919876543210",
      "ctc": "200000",
       "address": {
          "city": "Chennai",
          "country": "India"
          }
          }]
  tasks:
    - debug: 
        var: names|map (attribute='first')



