- name: Convert dictionary to nice YAML
  hosts: localhost
  tasks:
    - debug:
        msg: "{{ my_dict | to_nice_yaml(indent=2) }}"
      vars:
        my_dict:
          key1: value1
          key2: value2

