- name: Create users
  hosts: localhost
  gather_facts: no
  vars:
    users:
      user1:
        name: Alice
        uid: 1001
      user2:
        name: Bob
        uid: 1002
  tasks:
    - name: Create user {{ item.value.name }}
      user:
        name: "{{ item.value.name }}"
        uid: "{{ item.value.uid }}"
      with_dict: "{{ users }}"

